Use https for pre-commits
thoth-station/package-releases-job pull request #647
Opened 2022-07-26 16:16 UTC by VannTen

Git protocol is disabled on github

2022-07-26 16:16 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **pacospace** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @pacospace` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fpackage-releases-job).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/package-releases-job/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["pacospace"]} -->

2022-07-26 16:18 UTC, sesheta commented
@VannTen: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 0d18db4803762f10e8b6dac492cda87b49f3b567 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_package-releases-job/647/pre-commit/1551964721492529152) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=package-releases-job&pr=647). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AVannTen). Please help us and [open an issue](https://github.com/thoth-station/package-releases-job/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-07-27 09:25 UTC, sesheta commented
@VannTen: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 1f7c8e0a7ba9fc2cb91b919b8c3ce0d337a75488 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_package-releases-job/647/pre-commit/1552223464339804160) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=package-releases-job&pr=647). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AVannTen). Please help us and [open an issue](https://github.com/thoth-station/package-releases-job/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-07-27 09:54 UTC, sesheta commented
@VannTen: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 9c526a947bb93d9a7382f4b2cc6b5324d3a0db61 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_package-releases-job/647/pre-commit/1552230862693601280) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=package-releases-job&pr=647). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AVannTen). Please help us and [open an issue](https://github.com/thoth-station/package-releases-job/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-07-27 15:44 UTC, harshad16 requested changes
This looks great.
However, the pre-commit needs to update as well
https://github.com/thoth-station/package-releases-job/blob/b55f750f290be84acdcc620cbdd684ac11019ed8/.prow.yaml#L9
to version v0.14.3

2022-07-28 07:07 UTC, VannTen commented
I just found out yesterday late.
I was searching were that version was defined, and it hit me that I was
not seeing the error and other repos, so... grep found out ^

2022-07-29 16:33 UTC, harshad16 approved these changes
/lgtm
/approve
thanks :100:

2022-07-29 16:33 UTC, merged

2022-07-29 16:35 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/package-releases-job/pull/647#pullrequestreview-1055814350" title="Approved">harshad16</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **pacospace** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @pacospace` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fpackage-releases-job).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/package-releases-job/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["pacospace"]} -->